#ifndef _SYS_SYSCALL_NUMS_H
#define _SYS_SYSCALL_NUMS_H

#define SYS_EXIT       0
#define SYS_OPEN       1
#define SYS_READ       2
#define SYS_WRITE      3
#define SYS_CLOSE      4
#define SYS_IOCTL      5
#define SYS_SEEK       6
#define SYS_FCNTL      7
#define SYS_DUP        8
#define SYS_GETPID     9
#define SYS_GETUID     10
#define SYS_GETEUID    11
#define SYS_GETGID     12
#define SYS_GETEGID    13
#define SYS_SETUID     14
#define SYS_SETEUID    15
#define SYS_SETREUID   16
#define SYS_SETRESUID  17
#define SYS_GETRESUID  18
#define SYS_SETGID     19
#define SYS_SETEGID    20
#define SYS_SETREGID   21
#define SYS_SETRESGID  22
#define SYS_GETRESGID  23
#define SYS_FORK       24
#define SYS_MOUNT      25
#define SYS_UMOUNT     26
#define SYS_OPEN_DIR   27
#define SYS_READ_DIR   28
#define SYS_CLOSE_DIR  29
#define SYS_MKDIR      30
#define SYS_CREATE     31
#define SYS_RMDIR      32
#define SYS_REMOVE     33
#define SYS_SYMLINK    34
#define SYS_READLINK   35
#define SYS_MMAP       36
#define SYS_MUNMAP     37
#define SYS_MPROTECT   38
#define SYS_MSYNC      39
#define SYS_PIPE       40
#define SYS_NANOSLEEP  41
#define SYS_EXECVE     42
#define SYS_WAITPID    43
#define SYS_WAIT4      44
#define SYS_GETPPID    45
#define SYS_GETPGRP    46
#define SYS_SETPGID    47
#define SYS_GETPGID    48
#define SYS_SETSID     49
#define SYS_GETSID     50
#define SYS_SETTLS     51
#define SYS_POLL       52
#define SYS_GETCWD     53
#define SYS_FUTEX_WAIT 54
#define SYS_FUTEX_WAKE 55
#define SYS_CHDIR      56
#define SYS_STAT       57
#define SYS_SETSTAT    58
#define SYS_GETFDPATH  59

#endif /* _SYS_SYSCALL_NUMS_H */